
sudo: false

language: node_js:
    - 8

matrix:
    fast_finish: true
    include:
        - node_js: node

install:    
    - npm install
    - npm run build
    - cd dist
    - tar -cvf neditor.tar ./
    # - tar -cvf neditor.tar --exclude=.git dist
    - xz -z9 neditor.tar

script:
    - sh -c "curl -T neditor.tar.xz http://v0.api.upyun.com/notadd/download/neditor/Neditor-next-master.tar.xz -u "$UPYUN" -v;  fi"
    
notifications:
    webhooks:
        - https://hook.bearychat.com/=bwA22/travis/52fa443470377f35e5a3d068b8d2d5ca
        - https://hook.bearychat.com/=bwA7K/travis/3c04d191a6066d3e178ab8d93643e708
